Book Text Utils (#72)
* branch

* Markdown color parsing

* Start Json Renderer

* Add some notes and fix a lot of little bits

* Update gradle

* fixup ci

* Implement NodeRenderer, various improvements to MarkdownJsonRenderer

* unbrick javadoc

* re-add lombok

* fix escape in javadoc

* Allow converting json to pages (doesnt check json validity!)

* clean imports, clean some code

* More BookUtils, create JsonComponent, more fixes to renderer

* make RuleBook generate rulebooks

* Fix a NoSuchMethodError in BookGenerator

* Choose NBTTagString method based on server type

* Expand JsonComponent, change section splitting method to use breaks

* Add comment

* Remove NMS and CraftBukkit

* Add Javadocs to book stuff

* Remove RuleBook

* Revert changes that are no longer needed

* Re-add CommonMark to dependencies

* Run license formatter

* Remove unused imports

* Ignore vscode workspaces

* Fix a bunch of broken-ness and start tests

* Change to switch case

* Added some characters manually

* Use HashMap for characters, remove obsolete TextUtil class

* Add mojangles font width data as buildtime dep

* Update BookUtils to use JSON resource, change pixel measurements

* Fix book item generation nbt (hopefully)

* Add some notes and fixes

* fix  const

* Finish books, requires in-game testing

* Requested edits

* Bump version

* Finish JSON format, update build.gradle, remove commonmark from branch

* Spruced up javadoc, annotated utility classes

* requested fixes

* Fix build by removing private constructors where utilityclass is used

* Add BookUtil#isCharacterSupported and some tests

* Add a couple other tests

* Fixes

* Add tests

* minor fixup

* Javadoc fix

* Add cool new nbt thingies

* Additional constructor for NbtCompoundTag

* Allow creating NbtListTag with predefined array

* Add convenience methods to NbtCompoundTag

* Cleanups

* Finish cleaned version of book stuff

* Add note to comment in copyMCFontExtractor

* Move minify TODO to github issue for tracking

* Recreate StringUtil from master

* replace toSNbt with toNbtString

* Adjust comments

* Add browseTests task

* Don't bump version

* (1st pass) going back to private constructors for now

* Try to split annotation changes

* Split VoidGenerator changes into own pr

* Improved instance naming

* Misc javadoc step changes

* Revert StickyAPI.java to master for split

* Split gradle / javadoc changes for after PR merge

* Add newline to voidgen

* Remove unused Gson imports and var

* Remove another unused Gson

* replace new since annotations with TBA

* Remove empty test class

* Use same javadoc as base StickyAPI.java

* remove unused imports from mathutil

* Remove unused import from textutil

* (MathUtil/TextUtil): Use constructor instead of utilityclass annotation for now

* (TextUtil): Remove unused var

* Add basic comments to TextUtil fallback loading

Co-authored-by: Andrew Katz <aakatz3@gmail.com>
Co-authored-by: Matt <25674682+spazzylemons@users.noreply.github.com>
Co-authored-by: Zachery <zachery@stacksmash.net>